from typing import Protocol, runtime_checkable


@runtime_checkable
class IProjectAgent(Protocol):
    def execute(self, game_description: str) -> None: ...
    def get_prompt(self, game_description: str) -> str: ...
    def open(self) -> None: ...
    def close(self) -> None: ...