from ai_code_gen_sys.models.element import Element
from typing import Protocol, runtime_checkable

@runtime_checkable
class ITaskAgent(Protocol):
    def execute(self, element: Element) -> None: ...
    def get_prompt(self, element: Element) -> str: ...
    def open(self) -> None: ...
    def close(self) -> None: ...